---
- name: create remote user
  user:
    name: "{{ secure_deployment_user }}"
    shell: /bin/bash
    groups: sudo
    state: present
  become: yes

- name: give user passwordless sudo
  copy:
    content: '{{ secure_deployment_user }} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/{{ secure_deployment_user }}
    mode: 0440
  become: yes

- name: copy root's SSH dir to the user's
  copy:
    remote_src: yes
    src: /root/.ssh
    dest: "/home/{{ secure_deployment_user }}/.ssh"
    owner: "{{ secure_deployment_user }}"
    group: "{{ secure_deployment_user }}"
  become: yes

- name: copy sshd_config file to remote host
  copy:
    src: sshd_config
    dest: /etc/ssh/
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh
  become: yes

- name: install fail2ban
  apt:
    name: fail2ban
    state: present
  become: yes

- name: install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
  become: yes

- name: adjust APT update intervals
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
  become: yes

- name: install iptables
  apt:
    name: iptables
    state: present
  when: secure_install_iptables
  become: yes

- name: copy iptables rules file
  copy:
    src: iptables.rules
    dest: /etc/iptables.rules
  notify:
    - load iptables rules
  when: secure_install_iptables
  become: yes

- name: enable iptables rules at startup
  copy:
    src: firewall
    dest: /etc/network/if-pre-up.d/firewall
    mode: 0754
  when: secure_install_iptables
  become: yes
